name = "picpocket-worker"
main = "worker.js"
compatibility_date = "2023-05-22"

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "http://localhost:3000,https://solmasta.github.io"

[[d1_databases]]
binding = "DB"
database_name = "picpocket"
database_id = "0339a2cf-1007-4126-862b-99332f24a785"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "picpocket-photos"

[ai]
binding = "AI"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[dev]
port = 8787